export const RouteDefinitons = {
  ROUTE_TEACHER_LOGIN: "/teacher/login",
  ROUTE_TEACHER_SIGNUP: "/teacher/signup",
  ROUTE_TEACHER_DASHBOARD: "/teacher/dashboard",
  ROUTE_TEACHER_CREATE_CLASS: "/teacher/create-class",
  ROUTE_EVALUATOR_DASHBOARD: "/dashboard",
  ROUTE_STUDENT_LOGIN: "/student/login",
  ROUTE_STUDENT_SIGNUP: "/student/signup",
  ROUTE_STUDENT_DASHBOARD: "/student/dashboard",
  ROUTE_STUDENT_AWARDS: "/student/awards",
  ROUTE_STUDENT_SUBMIT_ANSWER: "/student/submit-answer",
  ROUTE_STUDENT_CREATE_MISSION: "/student/create-mission",
  ROUTE_STUDENT_CREATE_UNIT: "/student/create-unit",
  ROUTE_STUDENT_PRACTICE_DASHBOARD: "/student/practice-dashboard",
  ROUTE_STUDENT_PRACTICE_LIST: "/student/practice-list",
  ROUTE_STUDENT_REVISE: "/student/revise",
  ROUTE_STUDENT_COMPLETED_MISSIONS: "/student/completed-missions",
  ROUTE_STUDENT_CURRENT_MISSIONS: "/student/current-missions",
  ROUTE_STUDENT_PRACTICE: "/teacher/student-practice/:id",
  ROUTE_STUDENT_LIST: "/teacher/student-practice/",
  ROUTE_STUDENT_PRACTICE_DETAILED_REPORT: "/teacher/detailed-report/:id",
  ROUTE_TEACHER_ANSWER_KEYS: "/teacher/answer-keys",
  ROUTE_TEACHER_SUMMARY_REPORT: "/teacher/summary-report/:id",
  ROUTE_TEACHER_MANAGE_CLASS: "/teacher/manage-class",
  ROUTE_TEACHER_CLASS_DETAILS: "/teacher/manage-class/:id",
  ROUTE_TEACHER_ACCEPT_INVITE: "/teacher/accept-invite/:id",
};
