export const RouteDefinitions = {
  ROUTE_VIDEO_CALL: "/video-call",
  ROUTE_END_CALL: "/thank-you",
  ROUTE_DASHBOARD: "/dashboard",
  ROUTE_TUTOR_SUPPORT: "/tutor-support",
  ROUTE_HISTORY: "/history",
  ROUTE_SETTINGS: "/settings",
  ROUTE_LOGIN: "/login",
  ROUTE_LANDING: "/",
  ROUTE_LOGOUT: "/logout",
  ROUTE_CLIENT_DASHBOARD: "/client-dashboard",
  ROUTE_CLIENT_LOGIN: "/client-login",
  ROUTE_CLIENT_SIGN_UP: '/client-signup',
  ROUTE_CLIENT_MEETINGS: "/client-meetings",
  ROUTE_CLIENT_PAYMENT: "/client-payment",
  ROUTE_CLIENT_PAYMENT_LIST: "/client-payment-list",
};
